### ISSUE TITLE
Timeline for rest of components?

### ISSUE THREAD

**Issue by ajaishankar** [airblade/headlessui-stimulus#4]
Hi @airblade 

Love this initiative, thanks so much!

Just wanted to check if you are actively developing this, and plans for implementing the rest of the components.

I've been doing some work on Stimulus myself, mostly on the Typescript side of things.

[stimulus-reactive](https://github.com/ajaishankar/stimulus-reactive)
[stimulus-typescript](https://github.com/ajaishankar/stimulus-typescript)
[stimulus-zod-form](https://github.com/ajaishankar/stimulus-zod-form)

Would love to contribute in some way on this project...

Ajai

**Comment by airblade** [comment]
I am implementing each component as I need it, and maintaining what's already implemented.  I can't give a timeline.

It's all JavaScript and I don't plan to use Typescript.

Thanks for offering to contribute.  If there's an unimplemented component you need, you could implement it and open a pull request.  However I can't promise to review anything in a timely fashion.

**Comment by ajaishankar** [comment]
Thanks Andy

Will raise PR for any component I implement...

Ajai
